export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_ID = "GET_MOVIE_ID";
export const GET_RELEASES = "GET_RELEASES";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const CREATE_MOVIE = "CREATE_MOVIE";
export const AGE_CLASSIFICATION = "AGE_CLASSIFICATION";
export const GET_FOODS = "GET_FOODS";
export const GET_DRINKS = "GET_DRINKS";
export const GET_COMBOS = "GET_COMBOS";
export const SEARCH_FOOD = "SEARCH_FOOD";
export const GET_SEATS = "GET_SEATS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const LOGIN_OR_REGISTER_USER_WITH_GOOGLE =
  "LOGIN_OR_REGISTER_USER_WITH_GOOGLE";
export const REQUEST_GENRES2 = "REQUEST_GENRES2";
